name: ChatOps
on: [issue_comment]

jobs:
  run_evaluations:
    runs-on: ubuntu-18.04

    steps:
    - name: listen for PR Comments
      uses: machine-learning-apps/actions-chatops@master
      with:
        TRIGGER_PHRASE: "/evaluate"
      env: # you must supply GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: prcomm

    - name: Checkout
      if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      uses: actions/checkout@master

    - name: Setup python
      if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install requirements
      if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install -r requirements.txt

    - name: Evaluation
      if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      run: python evaluate.py
