name: Pull Requests

on:
  pull_request:
    branches:
    - master

jobs:
  run_tests:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@vmaster

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install -r requirements.txt

    - name: Flake
      run: python -m flake8 ./
